=== NerdyCrow/-2-/XML_2/Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="FACULTY">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SPECIALIZATION" type="xs:string" />
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="NAME" type="xs:string" />
                        <xs:element name="POINTS" type="xs:string" />
                        <xs:element name="COL" type="xs:string" />
                        <xs:element name="TOWN" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
    </xs:element>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== NerdyCrow/-2-/XML_2/лаба2_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
<FACULTY xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="Schema.xsd">

    <SPECIALIZATION>
        <NAME>ПГУ</NAME>
        <POINTS>285 баллов</POINTS>
        <COL>План набора: 18 человек</COL>
        <TOWN>Полоцк</TOWN>
    </SPECIALIZATION>
    <SPECIALIZATION>
        <NAME>БГТУ</NAME>
        <POINTS>335 баллов</POINTS>
        <COL>План набора: 32 человек</COL>
        <TOWN>Минск</TOWN>
    </SPECIALIZATION>
    <SPECIALIZATION>
        <NAME>БГУиР</NAME>
        <POINTS>352 баллов</POINTS>
        <COL>План набора: 28 человек</COL>
        <TOWN>Минск</TOWN>
    </SPECIALIZATION>

</FACULTY>
